Content-Type: multipart/mixed; boundary="//"
MIME-Version: 1.0

--//
Content-Type: text/cloud-config; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="config.yaml"

#cloud-config

users:
  - name: ansible
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBrfzsE8X9pEqYFfBlcnLzNL/dWv+cOekcazfu6O1AXfDnGPN9nzfnkgcZ0XPR8g++9LaX6duPZqARAjl34BFJEAjAQzPbx8hV0EBEXBcgmRpsqxpjgwyJhMPAaG6HvZ/cvkeLngFr2cG5Esx2lgjrg66BMcjvLspoQGuA6JhaOKa3ti6CIS+PhHjFqRspmw6EDBsx2mG1E1NXGgNbO6960/JXCv1xkryspfN+mdQZpseBpIaGDuDO6ThmSx6AWHZci/mlqo5xiJOAyKwR18uYEdvem3X1mnBBjnky2Mnhp1RBzsnlKULdRH1elQ/bB2nvVRXoUo8SIzuQ4txHJtPr
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

--//
Content-Type: text/x-shellscript; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: attachment; filename="script.sh"

#!/bin/bash

--//
